'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Login
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Truck_Out_Order.Login", GetType(Login).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to None.
        '''</summary>
        Friend Shared ReadOnly Property btnCancel_Anchor() As System.Windows.Forms.AnchorStyles
            Get
                Dim obj As Object = ResourceManager.GetObject("btnCancel.Anchor", resourceCulture)
                Return CType(obj,System.Windows.Forms.AnchorStyles)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Windows.Forms.FlatStyle similar to Flat.
        '''</summary>
        Friend Shared ReadOnly Property btnCancel_FlatStyle() As System.Windows.Forms.FlatStyle
            Get
                Dim obj As Object = ResourceManager.GetObject("btnCancel.FlatStyle", resourceCulture)
                Return CType(obj,System.Windows.Forms.FlatStyle)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Helvetica, Size=15, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        '''</summary>
        Friend Shared ReadOnly Property btnCancel_Font() As System.Drawing.Font
            Get
                Dim obj As Object = ResourceManager.GetObject("btnCancel.Font", resourceCulture)
                Return CType(obj,System.Drawing.Font)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Point similar to {X=155,Y=324}.
        '''</summary>
        Friend Shared ReadOnly Property btnCancel_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("btnCancel.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Size similar to {Width=85, Height=31}.
        '''</summary>
        Friend Shared ReadOnly Property btnCancel_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("btnCancel.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Int32 similar to 5.
        '''</summary>
        Friend Shared ReadOnly Property btnCancel_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("btnCancel.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancel.
        '''</summary>
        Friend Shared ReadOnly Property btnCancel_Text() As String
            Get
                Return ResourceManager.GetString("btnCancel.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to None.
        '''</summary>
        Friend Shared ReadOnly Property btnLogin_Anchor() As System.Windows.Forms.AnchorStyles
            Get
                Dim obj As Object = ResourceManager.GetObject("btnLogin.Anchor", resourceCulture)
                Return CType(obj,System.Windows.Forms.AnchorStyles)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Windows.Forms.FlatStyle similar to Flat.
        '''</summary>
        Friend Shared ReadOnly Property btnLogin_FlatStyle() As System.Windows.Forms.FlatStyle
            Get
                Dim obj As Object = ResourceManager.GetObject("btnLogin.FlatStyle", resourceCulture)
                Return CType(obj,System.Windows.Forms.FlatStyle)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Helvetica, Size=12, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        '''</summary>
        Friend Shared ReadOnly Property btnLogin_Font() As System.Drawing.Font
            Get
                Dim obj As Object = ResourceManager.GetObject("btnLogin.Font", resourceCulture)
                Return CType(obj,System.Drawing.Font)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Point similar to {X=55,Y=260}.
        '''</summary>
        Friend Shared ReadOnly Property btnLogin_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("btnLogin.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Size similar to {Width=285, Height=37}.
        '''</summary>
        Friend Shared ReadOnly Property btnLogin_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("btnLogin.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Int32 similar to 4.
        '''</summary>
        Friend Shared ReadOnly Property btnLogin_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("btnLogin.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SIGN IN.
        '''</summary>
        Friend Shared ReadOnly Property btnLogin_Text() As String
            Get
                Return ResourceManager.GetString("btnLogin.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to English.
        '''</summary>
        Friend Shared ReadOnly Property cmbLanguage_Items() As String
            Get
                Return ResourceManager.GetString("cmbLanguage.Items", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to French.
        '''</summary>
        Friend Shared ReadOnly Property cmbLanguage_Items1() As String
            Get
                Return ResourceManager.GetString("cmbLanguage.Items1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Point similar to {X=1105,Y=27}.
        '''</summary>
        Friend Shared ReadOnly Property cmbLanguage_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("cmbLanguage.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Size similar to {Width=121, Height=21}.
        '''</summary>
        Friend Shared ReadOnly Property cmbLanguage_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("cmbLanguage.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Int32 similar to 9.
        '''</summary>
        Friend Shared ReadOnly Property cmbLanguage_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("cmbLanguage.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Size similar to {Width=61, Height=4}.
        '''</summary>
        Friend Shared ReadOnly Property ContextMenuStrip1_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("ContextMenuStrip1.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Point similar to {X=17,Y=17}.
        '''</summary>
        Friend Shared ReadOnly Property ContextMenuStrip1_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("ContextMenuStrip1.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to None.
        '''</summary>
        Friend Shared ReadOnly Property lblLogin_Anchor() As System.Windows.Forms.AnchorStyles
            Get
                Dim obj As Object = ResourceManager.GetObject("lblLogin.Anchor", resourceCulture)
                Return CType(obj,System.Windows.Forms.AnchorStyles)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property lblLogin_AutoSize() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("lblLogin.AutoSize", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Helvetica, Size=17.25, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        '''</summary>
        Friend Shared ReadOnly Property lblLogin_Font() As System.Drawing.Font
            Get
                Dim obj As Object = ResourceManager.GetObject("lblLogin.Font", resourceCulture)
                Return CType(obj,System.Drawing.Font)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Point similar to {X=107,Y=16}.
        '''</summary>
        Friend Shared ReadOnly Property lblLogin_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("lblLogin.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Size similar to {Width=173, Height=27}.
        '''</summary>
        Friend Shared ReadOnly Property lblLogin_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("lblLogin.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Int32 similar to 6.
        '''</summary>
        Friend Shared ReadOnly Property lblLogin_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("lblLogin.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Account Login.
        '''</summary>
        Friend Shared ReadOnly Property lblLogin_Text() As String
            Get
                Return ResourceManager.GetString("lblLogin.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to None.
        '''</summary>
        Friend Shared ReadOnly Property lblPassword_Anchor() As System.Windows.Forms.AnchorStyles
            Get
                Dim obj As Object = ResourceManager.GetObject("lblPassword.Anchor", resourceCulture)
                Return CType(obj,System.Windows.Forms.AnchorStyles)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property lblPassword_AutoSize() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("lblPassword.AutoSize", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Helvetica, Size=15, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        '''</summary>
        Friend Shared ReadOnly Property lblPassword_Font() As System.Drawing.Font
            Get
                Dim obj As Object = ResourceManager.GetObject("lblPassword.Font", resourceCulture)
                Return CType(obj,System.Drawing.Font)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Point similar to {X=53,Y=170}.
        '''</summary>
        Friend Shared ReadOnly Property lblPassword_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("lblPassword.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Size similar to {Width=97, Height=24}.
        '''</summary>
        Friend Shared ReadOnly Property lblPassword_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("lblPassword.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Int32 similar to 1.
        '''</summary>
        Friend Shared ReadOnly Property lblPassword_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("lblPassword.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Password.
        '''</summary>
        Friend Shared ReadOnly Property lblPassword_Text() As String
            Get
                Return ResourceManager.GetString("lblPassword.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to None.
        '''</summary>
        Friend Shared ReadOnly Property lblTooSystem_Anchor() As System.Windows.Forms.AnchorStyles
            Get
                Dim obj As Object = ResourceManager.GetObject("lblTooSystem.Anchor", resourceCulture)
                Return CType(obj,System.Windows.Forms.AnchorStyles)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property lblTooSystem_AutoSize() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("lblTooSystem.AutoSize", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Times New Roman, Size=72, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        '''</summary>
        Friend Shared ReadOnly Property lblTooSystem_Font() As System.Drawing.Font
            Get
                Dim obj As Object = ResourceManager.GetObject("lblTooSystem.Font", resourceCulture)
                Return CType(obj,System.Drawing.Font)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Point similar to {X=93,Y=0}.
        '''</summary>
        Friend Shared ReadOnly Property lblTooSystem_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("lblTooSystem.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Size similar to {Width=1074, Height=109}.
        '''</summary>
        Friend Shared ReadOnly Property lblTooSystem_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("lblTooSystem.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Int32 similar to 2.
        '''</summary>
        Friend Shared ReadOnly Property lblTooSystem_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("lblTooSystem.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Truck Out Order System.
        '''</summary>
        Friend Shared ReadOnly Property lblTooSystem_Text() As String
            Get
                Return ResourceManager.GetString("lblTooSystem.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.ContentAlignment similar to MiddleCenter.
        '''</summary>
        Friend Shared ReadOnly Property lblTooSystem_TextAlign() As System.Drawing.ContentAlignment
            Get
                Dim obj As Object = ResourceManager.GetObject("lblTooSystem.TextAlign", resourceCulture)
                Return CType(obj,System.Drawing.ContentAlignment)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to None.
        '''</summary>
        Friend Shared ReadOnly Property lblUsername_Anchor() As System.Windows.Forms.AnchorStyles
            Get
                Dim obj As Object = ResourceManager.GetObject("lblUsername.Anchor", resourceCulture)
                Return CType(obj,System.Windows.Forms.AnchorStyles)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property lblUsername_AutoSize() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("lblUsername.AutoSize", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Helvetica, Size=15, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        '''</summary>
        Friend Shared ReadOnly Property lblUsername_Font() As System.Drawing.Font
            Get
                Dim obj As Object = ResourceManager.GetObject("lblUsername.Font", resourceCulture)
                Return CType(obj,System.Drawing.Font)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Point similar to {X=53,Y=87}.
        '''</summary>
        Friend Shared ReadOnly Property lblUsername_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("lblUsername.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Size similar to {Width=102, Height=24}.
        '''</summary>
        Friend Shared ReadOnly Property lblUsername_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("lblUsername.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Int32 similar to 0.
        '''</summary>
        Friend Shared ReadOnly Property lblUsername_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("lblUsername.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Username.
        '''</summary>
        Friend Shared ReadOnly Property lblUsername_Text() As String
            Get
                Return ResourceManager.GetString("lblUsername.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Top, Bottom, Left, Right.
        '''</summary>
        Friend Shared ReadOnly Property pbGCB_Anchor() As System.Windows.Forms.AnchorStyles
            Get
                Dim obj As Object = ResourceManager.GetObject("pbGCB.Anchor", resourceCulture)
                Return CType(obj,System.Windows.Forms.AnchorStyles)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Windows.Forms.ImageLayout similar to Stretch.
        '''</summary>
        Friend Shared ReadOnly Property pbGCB_BackgroundImageLayout() As System.Windows.Forms.ImageLayout
            Get
                Dim obj As Object = ResourceManager.GetObject("pbGCB.BackgroundImageLayout", resourceCulture)
                Return CType(obj,System.Windows.Forms.ImageLayout)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Point similar to {X=458,Y=3}.
        '''</summary>
        Friend Shared ReadOnly Property pbGCB_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("pbGCB.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Size similar to {Width=349, Height=124}.
        '''</summary>
        Friend Shared ReadOnly Property pbGCB_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("pbGCB.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Int32 similar to 8.
        '''</summary>
        Friend Shared ReadOnly Property pbGCB_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("pbGCB.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Top, Bottom, Left, Right.
        '''</summary>
        Friend Shared ReadOnly Property pnlLogin_Anchor() As System.Windows.Forms.AnchorStyles
            Get
                Dim obj As Object = ResourceManager.GetObject("pnlLogin.Anchor", resourceCulture)
                Return CType(obj,System.Windows.Forms.AnchorStyles)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Point similar to {X=435,Y=249}.
        '''</summary>
        Friend Shared ReadOnly Property pnlLogin_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("pnlLogin.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Size similar to {Width=394, Height=387}.
        '''</summary>
        Friend Shared ReadOnly Property pnlLogin_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("pnlLogin.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Int32 similar to 7.
        '''</summary>
        Friend Shared ReadOnly Property pnlLogin_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("pnlLogin.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Int32 similar to 1.
        '''</summary>
        Friend Shared ReadOnly Property TableLayoutPanel1_ColumnCount() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("TableLayoutPanel1.ColumnCount", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Windows.Forms.TableLayoutSettings.
        '''</summary>
        Friend Shared ReadOnly Property TableLayoutPanel1_LayoutSettings() As System.Windows.Forms.TableLayoutSettings
            Get
                Dim obj As Object = ResourceManager.GetObject("TableLayoutPanel1.LayoutSettings", resourceCulture)
                Return CType(obj,System.Windows.Forms.TableLayoutSettings)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Point similar to {X=2,Y=133}.
        '''</summary>
        Friend Shared ReadOnly Property TableLayoutPanel1_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("TableLayoutPanel1.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Int32 similar to 1.
        '''</summary>
        Friend Shared ReadOnly Property TableLayoutPanel1_RowCount() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("TableLayoutPanel1.RowCount", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Size similar to {Width=1261, Height=110}.
        '''</summary>
        Friend Shared ReadOnly Property TableLayoutPanel1_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("TableLayoutPanel1.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Int32 similar to 10.
        '''</summary>
        Friend Shared ReadOnly Property TableLayoutPanel1_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("TableLayoutPanel1.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Int32 similar to 1.
        '''</summary>
        Friend Shared ReadOnly Property TableLayoutPanel2_ColumnCount() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("TableLayoutPanel2.ColumnCount", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Windows.Forms.TableLayoutSettings.
        '''</summary>
        Friend Shared ReadOnly Property TableLayoutPanel2_LayoutSettings() As System.Windows.Forms.TableLayoutSettings
            Get
                Dim obj As Object = ResourceManager.GetObject("TableLayoutPanel2.LayoutSettings", resourceCulture)
                Return CType(obj,System.Windows.Forms.TableLayoutSettings)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Point similar to {X=3,Y=11}.
        '''</summary>
        Friend Shared ReadOnly Property TableLayoutPanel2_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("TableLayoutPanel2.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Int32 similar to 1.
        '''</summary>
        Friend Shared ReadOnly Property TableLayoutPanel2_RowCount() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("TableLayoutPanel2.RowCount", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Size similar to {Width=388, Height=60}.
        '''</summary>
        Friend Shared ReadOnly Property TableLayoutPanel2_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("TableLayoutPanel2.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Int32 similar to 11.
        '''</summary>
        Friend Shared ReadOnly Property TableLayoutPanel2_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("TableLayoutPanel2.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to None.
        '''</summary>
        Friend Shared ReadOnly Property tbPassword_Anchor() As System.Windows.Forms.AnchorStyles
            Get
                Dim obj As Object = ResourceManager.GetObject("tbPassword.Anchor", resourceCulture)
                Return CType(obj,System.Windows.Forms.AnchorStyles)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Helvetica, Size=15, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        '''</summary>
        Friend Shared ReadOnly Property tbPassword_Font() As System.Drawing.Font
            Get
                Dim obj As Object = ResourceManager.GetObject("tbPassword.Font", resourceCulture)
                Return CType(obj,System.Drawing.Font)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Point similar to {X=57,Y=197}.
        '''</summary>
        Friend Shared ReadOnly Property tbPassword_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("tbPassword.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Char similar to *.
        '''</summary>
        Friend Shared ReadOnly Property tbPassword_PasswordChar() As Char
            Get
                Dim obj As Object = ResourceManager.GetObject("tbPassword.PasswordChar", resourceCulture)
                Return CType(obj,Char)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Size similar to {Width=285, Height=31}.
        '''</summary>
        Friend Shared ReadOnly Property tbPassword_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("tbPassword.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Int32 similar to 3.
        '''</summary>
        Friend Shared ReadOnly Property tbPassword_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("tbPassword.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to None.
        '''</summary>
        Friend Shared ReadOnly Property tbUsername_Anchor() As System.Windows.Forms.AnchorStyles
            Get
                Dim obj As Object = ResourceManager.GetObject("tbUsername.Anchor", resourceCulture)
                Return CType(obj,System.Windows.Forms.AnchorStyles)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Helvetica, Size=15, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        '''</summary>
        Friend Shared ReadOnly Property tbUsername_Font() As System.Drawing.Font
            Get
                Dim obj As Object = ResourceManager.GetObject("tbUsername.Font", resourceCulture)
                Return CType(obj,System.Drawing.Font)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Point similar to {X=57,Y=114}.
        '''</summary>
        Friend Shared ReadOnly Property tbUsername_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("tbUsername.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Size similar to {Width=285, Height=31}.
        '''</summary>
        Friend Shared ReadOnly Property tbUsername_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("tbUsername.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Int32 similar to 2.
        '''</summary>
        Friend Shared ReadOnly Property tbUsername_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("tbUsername.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
    End Class
End Namespace
