'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class ResourceSecurityEditFrench
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Truck_Out_Order.ResourceSecurityEditFrench", GetType(ResourceSecurityEditFrench).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Annuler.
        '''</summary>
        Friend Shared ReadOnly Property btnCancel() As String
            Get
                Return ResourceManager.GetString("btnCancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Poste.
        '''</summary>
        Friend Shared ReadOnly Property btnPost() As String
            Get
                Return ResourceManager.GetString("btnPost", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Imprimer.
        '''</summary>
        Friend Shared ReadOnly Property btnPrint() As String
            Get
                Return ResourceManager.GetString("btnPrint", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sauvegarder.
        '''</summary>
        Friend Shared ReadOnly Property btnSave() As String
            Get
                Return ResourceManager.GetString("btnSave", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nom complet de l&apos;entreprise :.
        '''</summary>
        Friend Shared ReadOnly Property lblCompanyFullName() As String
            Get
                Return ResourceManager.GetString("lblCompanyFullName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Compagnie:.
        '''</summary>
        Friend Shared ReadOnly Property lblCompnay() As String
            Get
                Return ResourceManager.GetString("lblCompnay", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Numéro de conteneur.
        '''</summary>
        Friend Shared ReadOnly Property lblContainerNo() As String
            Get
                Return ResourceManager.GetString("lblContainerNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Taille du conteneur:.
        '''</summary>
        Friend Shared ReadOnly Property lblContainerSize() As String
            Get
                Return ResourceManager.GetString("lblContainerSize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DDB:.
        '''</summary>
        Friend Shared ReadOnly Property lblDDB() As String
            Get
                Return ResourceManager.GetString("lblDDB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vérification du conducteur.
        '''</summary>
        Friend Shared ReadOnly Property lblDriverCheck() As String
            Get
                Return ResourceManager.GetString("lblDriverCheck", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Numéro de sceau ES.
        '''</summary>
        Friend Shared ReadOnly Property lblEsSealNo() As String
            Get
                Return ResourceManager.GetString("lblEsSealNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nom complet du conducteur.
        '''</summary>
        Friend Shared ReadOnly Property lblFullName() As String
            Get
                Return ResourceManager.GetString("lblFullName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Transporteur.
        '''</summary>
        Friend Shared ReadOnly Property lblHaulier() As String
            Get
                Return ResourceManager.GetString("lblHaulier", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Numéro de joint interne.
        '''</summary>
        Friend Shared ReadOnly Property lblInternalSealNo() As String
            Get
                Return ResourceManager.GetString("lblInternalSealNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Facture d&apos;achat:.
        '''</summary>
        Friend Shared ReadOnly Property lblInvoice() As String
            Get
                Return ResourceManager.GetString("lblInvoice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Réservoir ISO :.
        '''</summary>
        Friend Shared ReadOnly Property lblISOTank() As String
            Get
                Return ResourceManager.GetString("lblISOTank", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Poids du réservoir ISO (mt):.
        '''</summary>
        Friend Shared ReadOnly Property lblISOTankWeight() As String
            Get
                Return ResourceManager.GetString("lblISOTankWeight", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vérification du poids du réservoir ISO.
        '''</summary>
        Friend Shared ReadOnly Property lblISOTankWeightCheck() As String
            Get
                Return ResourceManager.GetString("lblISOTankWeightCheck", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Date de sortie du camion :.
        '''</summary>
        Friend Shared ReadOnly Property lblISOTruckOutDate() As String
            Get
                Return ResourceManager.GetString("lblISOTruckOutDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vérification de la date ISO.
        '''</summary>
        Friend Shared ReadOnly Property lblISOTruckOutDateCheck() As String
            Get
                Return ResourceManager.GetString("lblISOTruckOutDateCheck", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chargement de la date de fin.
        '''</summary>
        Friend Shared ReadOnly Property lblLCD() As String
            Get
                Return ResourceManager.GetString("lblLCD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Temps de chargement terminé.
        '''</summary>
        Friend Shared ReadOnly Property lblLCT() As String
            Get
                Return ResourceManager.GetString("lblLCT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Numéro de joint de revêtement.
        '''</summary>
        Friend Shared ReadOnly Property lblLinerSealNo() As String
            Get
                Return ResourceManager.GetString("lblLinerSealNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Quai de chargement:.
        '''</summary>
        Friend Shared ReadOnly Property lblLoadingBay() As String
            Get
                Return ResourceManager.GetString("lblLoadingBay", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Port de chargement:.
        '''</summary>
        Friend Shared ReadOnly Property lblLoadingPort() As String
            Get
                Return ResourceManager.GetString("lblLoadingPort", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Poids net de la cargaison (kg) :.
        '''</summary>
        Friend Shared ReadOnly Property lblNetCargoWeight() As String
            Get
                Return ResourceManager.GetString("lblNetCargoWeight", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Code PM.
        '''</summary>
        Friend Shared ReadOnly Property lblPMCode() As String
            Get
                Return ResourceManager.GetString("lblPMCode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Plaque d&apos;immatriculation PM.
        '''</summary>
        Friend Shared ReadOnly Property lblPMRegistrationPlate() As String
            Get
                Return ResourceManager.GetString("lblPMRegistrationPlate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nom complet du port de chargement :.
        '''</summary>
        Friend Shared ReadOnly Property lblPortFullName() As String
            Get
                Return ResourceManager.GetString("lblPortFullName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Produit:.
        '''</summary>
        Friend Shared ReadOnly Property lblProduct() As String
            Get
                Return ResourceManager.GetString("lblProduct", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Date de sortie du camion prêt.
        '''</summary>
        Friend Shared ReadOnly Property lblRTD() As String
            Get
                Return ResourceManager.GetString("lblRTD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Temps de sortie du camion prêt.
        '''</summary>
        Friend Shared ReadOnly Property lblRTT() As String
            Get
                Return ResourceManager.GetString("lblRTT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Date limite d&apos;expédition :.
        '''</summary>
        Friend Shared ReadOnly Property lblSCD() As String
            Get
                Return ResourceManager.GetString("lblSCD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Heure de clôture de l&apos;expédition :.
        '''</summary>
        Friend Shared ReadOnly Property lblSCT() As String
            Get
                Return ResourceManager.GetString("lblSCT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vérification de sécurité.
        '''</summary>
        Friend Shared ReadOnly Property lblSecurityCheck() As String
            Get
                Return ResourceManager.GetString("lblSecurityCheck", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Poste de sécurité.
        '''</summary>
        Friend Shared ReadOnly Property lblSecurityPost() As String
            Get
                Return ResourceManager.GetString("lblSecurityPost", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Envoyer à l&apos;entreprise :.
        '''</summary>
        Friend Shared ReadOnly Property lblSendToCompany() As String
            Get
                Return ResourceManager.GetString("lblSendToCompany", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ligne maritime:.
        '''</summary>
        Friend Shared ReadOnly Property lblShippingLine() As String
            Get
                Return ResourceManager.GetString("lblShippingLine", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Poste d&apos;expédition.
        '''</summary>
        Friend Shared ReadOnly Property lblShippingPost() As String
            Get
                Return ResourceManager.GetString("lblShippingPost", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Numéro de sceau temporaire.
        '''</summary>
        Friend Shared ReadOnly Property lblTemporarySealNo() As String
            Get
                Return ResourceManager.GetString("lblTemporarySealNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Numéro de sortie du camion :.
        '''</summary>
        Friend Shared ReadOnly Property lblTruckOutNumber() As String
            Get
                Return ResourceManager.GetString("lblTruckOutNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Emplacement de l&apos;entrepôt :.
        '''</summary>
        Friend Shared ReadOnly Property lblWarehouseLocation() As String
            Get
                Return ResourceManager.GetString("lblWarehouseLocation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Poste d&apos;entrepôt.
        '''</summary>
        Friend Shared ReadOnly Property lblWarehousePost() As String
            Get
                Return ResourceManager.GetString("lblWarehousePost", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ce numéro peut être affiché par la sécurité maintenant.
        '''</summary>
        Friend Shared ReadOnly Property stringCanBePosted() As String
            Get
                Return ResourceManager.GetString("stringCanBePosted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vérification terminée.
        '''</summary>
        Friend Shared ReadOnly Property stringCheckComplete() As String
            Get
                Return ResourceManager.GetString("stringCheckComplete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Veuillez vérifier le numéro du conteneur.
        '''</summary>
        Friend Shared ReadOnly Property stringCheckContainerNo() As String
            Get
                Return ResourceManager.GetString("stringCheckContainerNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Veuillez vérifier le nom complet du conducteur.
        '''</summary>
        Friend Shared ReadOnly Property stringCheckDriverFullName() As String
            Get
                Return ResourceManager.GetString("stringCheckDriverFullName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Veuillez vérifier le numéro de sceau ES.
        '''</summary>
        Friend Shared ReadOnly Property stringCheckESSealNo() As String
            Get
                Return ResourceManager.GetString("stringCheckESSealNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Échec de la vérification.
        '''</summary>
        Friend Shared ReadOnly Property stringCheckFail() As String
            Get
                Return ResourceManager.GetString("stringCheckFail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vérifier l&apos;échec.
        '''</summary>
        Friend Shared ReadOnly Property stringCheckFailure() As String
            Get
                Return ResourceManager.GetString("stringCheckFailure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Veuillez vérifier le numéro de sceau interne..
        '''</summary>
        Friend Shared ReadOnly Property stringCheckInternalSealNo() As String
            Get
                Return ResourceManager.GetString("stringCheckInternalSealNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Veuillez vérifier le numéro de sceau de la doublure.
        '''</summary>
        Friend Shared ReadOnly Property stringCheckLinerSealNo() As String
            Get
                Return ResourceManager.GetString("stringCheckLinerSealNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Veuillez vérifier le code PM.
        '''</summary>
        Friend Shared ReadOnly Property stringCheckPMCode() As String
            Get
                Return ResourceManager.GetString("stringCheckPMCode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Veuillez vérifier la plaque d&apos;immatriculation PM.
        '''</summary>
        Friend Shared ReadOnly Property stringCheckPMRegistrationPlate() As String
            Get
                Return ResourceManager.GetString("stringCheckPMRegistrationPlate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Voulez-vous vraiment quitter ?.
        '''</summary>
        Friend Shared ReadOnly Property stringCheckQuit() As String
            Get
                Return ResourceManager.GetString("stringCheckQuit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Veuillez vérifier le contrôle de sécurité.
        '''</summary>
        Friend Shared ReadOnly Property stringCheckSecurityCheck() As String
            Get
                Return ResourceManager.GetString("stringCheckSecurityCheck", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Veuillez vérifier le numéro du sceau temporaire.
        '''</summary>
        Friend Shared ReadOnly Property stringCheckTemporarySealNo() As String
            Get
                Return ResourceManager.GetString("stringCheckTemporarySealNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fermer l&apos;application.
        '''</summary>
        Friend Shared ReadOnly Property stringCloseApplication() As String
            Get
                Return ResourceManager.GetString("stringCloseApplication", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Compléter.
        '''</summary>
        Friend Shared ReadOnly Property stringComplete() As String
            Get
                Return ResourceManager.GetString("stringComplete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Échec de la validation du pilote.
        '''</summary>
        Friend Shared ReadOnly Property stringDriverValidationFail() As String
            Get
                Return ResourceManager.GetString("stringDriverValidationFail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Laissez-passer de validation du conducteur.
        '''</summary>
        Friend Shared ReadOnly Property stringDriverValidationPass() As String
            Get
                Return ResourceManager.GetString("stringDriverValidationPass", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Veuillez remplir le champ du poids net de la cargaison.
        '''</summary>
        Friend Shared ReadOnly Property stringFillCargoWeight() As String
            Get
                Return ResourceManager.GetString("stringFillCargoWeight", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Veuillez informer l&apos;administrateur de l&apos;expédition.
        '''</summary>
        Friend Shared ReadOnly Property stringInformShippingAdmin() As String
            Get
                Return ResourceManager.GetString("stringInformShippingAdmin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Veuillez informer l&apos;administrateur de l&apos;entrepôt.
        '''</summary>
        Friend Shared ReadOnly Property stringInformWarehouseAdmin() As String
            Get
                Return ResourceManager.GetString("stringInformWarehouseAdmin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vérification de sécurité ISO terminée.
        '''</summary>
        Friend Shared ReadOnly Property stringISOCheckComplete() As String
            Get
                Return ResourceManager.GetString("stringISOCheckComplete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Échec de la vérification ISO.
        '''</summary>
        Friend Shared ReadOnly Property stringISOCheckFailed() As String
            Get
                Return ResourceManager.GetString("stringISOCheckFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Échec de la vérification du poids net de la cargaison.
        '''</summary>
        Friend Shared ReadOnly Property stringNetCargoCheckFailed() As String
            Get
                Return ResourceManager.GetString("stringNetCargoCheckFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Publication terminée.
        '''</summary>
        Friend Shared ReadOnly Property stringPostComplete() As String
            Get
                Return ResourceManager.GetString("stringPostComplete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Échec de la publication.
        '''</summary>
        Friend Shared ReadOnly Property stringPostFailed() As String
            Get
                Return ResourceManager.GetString("stringPostFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vérification de sécurité terminée.
        '''</summary>
        Friend Shared ReadOnly Property stringSecurityCheckComplete() As String
            Get
                Return ResourceManager.GetString("stringSecurityCheckComplete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Arrêter CTNR / Informer Entrepôt.
        '''</summary>
        Friend Shared ReadOnly Property stringStopCTNR() As String
            Get
                Return ResourceManager.GetString("stringStopCTNR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Erreur de date de sortie du camion.
        '''</summary>
        Friend Shared ReadOnly Property stringTruckOutDateError() As String
            Get
                Return ResourceManager.GetString("stringTruckOutDateError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mise à jour terminée.
        '''</summary>
        Friend Shared ReadOnly Property stringUpdateComplete() As String
            Get
                Return ResourceManager.GetString("stringUpdateComplete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Échec de la mise à jour.
        '''</summary>
        Friend Shared ReadOnly Property stringUpdateFailure() As String
            Get
                Return ResourceManager.GetString("stringUpdateFailure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Échec de la validation.
        '''</summary>
        Friend Shared ReadOnly Property stringValidationFail() As String
            Get
                Return ResourceManager.GetString("stringValidationFail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Laissez-passer de validation.
        '''</summary>
        Friend Shared ReadOnly Property stringValidationPass() As String
            Get
                Return ResourceManager.GetString("stringValidationPass", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
