'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class ResourceCommonEnglish
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Truck_Out_Order.ResourceCommonEnglish", GetType(ResourceCommonEnglish).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancel.
        '''</summary>
        Friend Shared ReadOnly Property btnCancel() As String
            Get
                Return ResourceManager.GetString("btnCancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Post.
        '''</summary>
        Friend Shared ReadOnly Property btnPost() As String
            Get
                Return ResourceManager.GetString("btnPost", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save.
        '''</summary>
        Friend Shared ReadOnly Property btnSave() As String
            Get
                Return ResourceManager.GetString("btnSave", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Company:.
        '''</summary>
        Friend Shared ReadOnly Property lblCompnay() As String
            Get
                Return ResourceManager.GetString("lblCompnay", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Container No..
        '''</summary>
        Friend Shared ReadOnly Property lblContainerNo() As String
            Get
                Return ResourceManager.GetString("lblContainerNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Container Size:.
        '''</summary>
        Friend Shared ReadOnly Property lblContainerSize() As String
            Get
                Return ResourceManager.GetString("lblContainerSize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DDB:.
        '''</summary>
        Friend Shared ReadOnly Property lblDDB() As String
            Get
                Return ResourceManager.GetString("lblDDB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ES Seal No..
        '''</summary>
        Friend Shared ReadOnly Property lblEsSealNo() As String
            Get
                Return ResourceManager.GetString("lblEsSealNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Company Full Name:.
        '''</summary>
        Friend Shared ReadOnly Property lblFullName() As String
            Get
                Return ResourceManager.GetString("lblFullName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Haulier:.
        '''</summary>
        Friend Shared ReadOnly Property lblHaulier() As String
            Get
                Return ResourceManager.GetString("lblHaulier", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Internal Seal No..
        '''</summary>
        Friend Shared ReadOnly Property lblInternalSealNo() As String
            Get
                Return ResourceManager.GetString("lblInternalSealNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invoice:.
        '''</summary>
        Friend Shared ReadOnly Property lblInvoice() As String
            Get
                Return ResourceManager.GetString("lblInvoice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ISO Tank:.
        '''</summary>
        Friend Shared ReadOnly Property lblISOTank() As String
            Get
                Return ResourceManager.GetString("lblISOTank", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ISO Tank Weight (mt):.
        '''</summary>
        Friend Shared ReadOnly Property lblISOTankWeight() As String
            Get
                Return ResourceManager.GetString("lblISOTankWeight", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Truck Out Date:.
        '''</summary>
        Friend Shared ReadOnly Property lblISOTruckOutDate() As String
            Get
                Return ResourceManager.GetString("lblISOTruckOutDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Liner&apos;s Seal No..
        '''</summary>
        Friend Shared ReadOnly Property lblLinerSealNo() As String
            Get
                Return ResourceManager.GetString("lblLinerSealNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Loading Bay:.
        '''</summary>
        Friend Shared ReadOnly Property lblLoadingBay() As String
            Get
                Return ResourceManager.GetString("lblLoadingBay", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Loading Port:.
        '''</summary>
        Friend Shared ReadOnly Property lblLoadingPort() As String
            Get
                Return ResourceManager.GetString("lblLoadingPort", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Net Cargo Weight (kg):.
        '''</summary>
        Friend Shared ReadOnly Property lblNetCargoWeight() As String
            Get
                Return ResourceManager.GetString("lblNetCargoWeight", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Loading Port Full Name:.
        '''</summary>
        Friend Shared ReadOnly Property lblPortFullName() As String
            Get
                Return ResourceManager.GetString("lblPortFullName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Product:.
        '''</summary>
        Friend Shared ReadOnly Property lblProduct() As String
            Get
                Return ResourceManager.GetString("lblProduct", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Shipment Closing Date:.
        '''</summary>
        Friend Shared ReadOnly Property lblSCD() As String
            Get
                Return ResourceManager.GetString("lblSCD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Shipment Closing Time:.
        '''</summary>
        Friend Shared ReadOnly Property lblSCT() As String
            Get
                Return ResourceManager.GetString("lblSCT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Send To Company:.
        '''</summary>
        Friend Shared ReadOnly Property lblSendToCompany() As String
            Get
                Return ResourceManager.GetString("lblSendToCompany", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Shipping Line:.
        '''</summary>
        Friend Shared ReadOnly Property lblShippingLine() As String
            Get
                Return ResourceManager.GetString("lblShippingLine", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Temporary Seal No,.
        '''</summary>
        Friend Shared ReadOnly Property lblTemporarySealNo() As String
            Get
                Return ResourceManager.GetString("lblTemporarySealNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Truck Out Number:.
        '''</summary>
        Friend Shared ReadOnly Property lblTruckOutNumber() As String
            Get
                Return ResourceManager.GetString("lblTruckOutNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Warehouse Location:.
        '''</summary>
        Friend Shared ReadOnly Property lblWarehouseLocation() As String
            Get
                Return ResourceManager.GetString("lblWarehouseLocation", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
