'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class ResourceSecurityEdit
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Truck_Out_Order.ResourceSecurityEdit", GetType(ResourceSecurityEdit).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancel.
        '''</summary>
        Public Shared ReadOnly Property btnCancel() As String
            Get
                Return ResourceManager.GetString("btnCancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Post.
        '''</summary>
        Public Shared ReadOnly Property btnPost() As String
            Get
                Return ResourceManager.GetString("btnPost", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Print.
        '''</summary>
        Public Shared ReadOnly Property btnPrint() As String
            Get
                Return ResourceManager.GetString("btnPrint", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save.
        '''</summary>
        Public Shared ReadOnly Property btnSave() As String
            Get
                Return ResourceManager.GetString("btnSave", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Company Full Name:.
        '''</summary>
        Public Shared ReadOnly Property lblCompanyFullName1() As String
            Get
                Return ResourceManager.GetString("lblCompanyFullName1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Company:.
        '''</summary>
        Public Shared ReadOnly Property lblCompnay() As String
            Get
                Return ResourceManager.GetString("lblCompnay", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Container No..
        '''</summary>
        Public Shared ReadOnly Property lblContainerNo() As String
            Get
                Return ResourceManager.GetString("lblContainerNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Container Size:.
        '''</summary>
        Public Shared ReadOnly Property lblContainerSize() As String
            Get
                Return ResourceManager.GetString("lblContainerSize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DDB:.
        '''</summary>
        Public Shared ReadOnly Property lblDDB() As String
            Get
                Return ResourceManager.GetString("lblDDB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Driver Check.
        '''</summary>
        Public Shared ReadOnly Property lblDriverCheck() As String
            Get
                Return ResourceManager.GetString("lblDriverCheck", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ES Seal No..
        '''</summary>
        Public Shared ReadOnly Property lblEsSealNo() As String
            Get
                Return ResourceManager.GetString("lblEsSealNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Driver Full Name:.
        '''</summary>
        Public Shared ReadOnly Property lblFullName() As String
            Get
                Return ResourceManager.GetString("lblFullName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Haulier:.
        '''</summary>
        Public Shared ReadOnly Property lblHaulier() As String
            Get
                Return ResourceManager.GetString("lblHaulier", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Internal Seal No..
        '''</summary>
        Public Shared ReadOnly Property lblInternalSealNo() As String
            Get
                Return ResourceManager.GetString("lblInternalSealNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invoice:.
        '''</summary>
        Public Shared ReadOnly Property lblInvoice() As String
            Get
                Return ResourceManager.GetString("lblInvoice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ISO Check.
        '''</summary>
        Public Shared ReadOnly Property lblISOCheck() As String
            Get
                Return ResourceManager.GetString("lblISOCheck", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ISO Tank:.
        '''</summary>
        Public Shared ReadOnly Property lblISOTank() As String
            Get
                Return ResourceManager.GetString("lblISOTank", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ISO Tank Weight (mt):.
        '''</summary>
        Public Shared ReadOnly Property lblISOTankWeight() As String
            Get
                Return ResourceManager.GetString("lblISOTankWeight", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ISO Tank Weight Check:.
        '''</summary>
        Public Shared ReadOnly Property lblISOTankWeightCheck() As String
            Get
                Return ResourceManager.GetString("lblISOTankWeightCheck", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Truck Out Date:.
        '''</summary>
        Public Shared ReadOnly Property lblISOTruckOutDate() As String
            Get
                Return ResourceManager.GetString("lblISOTruckOutDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Truck Out Date Check:.
        '''</summary>
        Public Shared ReadOnly Property lblISOTruckOutDateCheck() As String
            Get
                Return ResourceManager.GetString("lblISOTruckOutDateCheck", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Loading Completed Date.
        '''</summary>
        Public Shared ReadOnly Property lblLCD() As String
            Get
                Return ResourceManager.GetString("lblLCD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Loading Completed Time.
        '''</summary>
        Public Shared ReadOnly Property lblLCT() As String
            Get
                Return ResourceManager.GetString("lblLCT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Liner&apos;s Seal No..
        '''</summary>
        Public Shared ReadOnly Property lblLinerSealNo() As String
            Get
                Return ResourceManager.GetString("lblLinerSealNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Loading Bay:.
        '''</summary>
        Public Shared ReadOnly Property lblLoadingBay() As String
            Get
                Return ResourceManager.GetString("lblLoadingBay", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Loading Port:.
        '''</summary>
        Public Shared ReadOnly Property lblLoadingPort() As String
            Get
                Return ResourceManager.GetString("lblLoadingPort", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Net Cargo Weight (kg):.
        '''</summary>
        Public Shared ReadOnly Property lblNetCargoWeight() As String
            Get
                Return ResourceManager.GetString("lblNetCargoWeight", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PM Code.
        '''</summary>
        Public Shared ReadOnly Property lblPMCode() As String
            Get
                Return ResourceManager.GetString("lblPMCode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PM Registration Plate.
        '''</summary>
        Public Shared ReadOnly Property lblPMRegistrationPlate() As String
            Get
                Return ResourceManager.GetString("lblPMRegistrationPlate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Loading Port Full Name:.
        '''</summary>
        Public Shared ReadOnly Property lblPortFullName() As String
            Get
                Return ResourceManager.GetString("lblPortFullName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Product:.
        '''</summary>
        Public Shared ReadOnly Property lblProduct() As String
            Get
                Return ResourceManager.GetString("lblProduct", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ready Truck Out Date.
        '''</summary>
        Public Shared ReadOnly Property lblRTD() As String
            Get
                Return ResourceManager.GetString("lblRTD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ready Truck Out TIme.
        '''</summary>
        Public Shared ReadOnly Property lblRTT() As String
            Get
                Return ResourceManager.GetString("lblRTT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Shipment Closing Date:.
        '''</summary>
        Public Shared ReadOnly Property lblSCD() As String
            Get
                Return ResourceManager.GetString("lblSCD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Shipment Closing Time:.
        '''</summary>
        Public Shared ReadOnly Property lblSCT() As String
            Get
                Return ResourceManager.GetString("lblSCT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Security Check.
        '''</summary>
        Public Shared ReadOnly Property lblSecurityCheck() As String
            Get
                Return ResourceManager.GetString("lblSecurityCheck", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Security Post.
        '''</summary>
        Public Shared ReadOnly Property lblSecurityPost() As String
            Get
                Return ResourceManager.GetString("lblSecurityPost", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Send To Company:.
        '''</summary>
        Public Shared ReadOnly Property lblSendToCompany() As String
            Get
                Return ResourceManager.GetString("lblSendToCompany", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Shipping Line:.
        '''</summary>
        Public Shared ReadOnly Property lblShippingLine() As String
            Get
                Return ResourceManager.GetString("lblShippingLine", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Shipping Post.
        '''</summary>
        Public Shared ReadOnly Property lblShippingPost() As String
            Get
                Return ResourceManager.GetString("lblShippingPost", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Temporary Seal No,.
        '''</summary>
        Public Shared ReadOnly Property lblTemporarySealNo() As String
            Get
                Return ResourceManager.GetString("lblTemporarySealNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Truck Out Number:.
        '''</summary>
        Public Shared ReadOnly Property lblTruckOutNumber() As String
            Get
                Return ResourceManager.GetString("lblTruckOutNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Warehouse Location:.
        '''</summary>
        Public Shared ReadOnly Property lblWarehouseLocation() As String
            Get
                Return ResourceManager.GetString("lblWarehouseLocation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Warehouse Post.
        '''</summary>
        Public Shared ReadOnly Property lblWarehousePost() As String
            Get
                Return ResourceManager.GetString("lblWarehousePost", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This Number Can Be Posted By Security Now.
        '''</summary>
        Public Shared ReadOnly Property stringCanBePosted() As String
            Get
                Return ResourceManager.GetString("stringCanBePosted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cargo Approve.
        '''</summary>
        Public Shared ReadOnly Property stringCargoApprove() As String
            Get
                Return ResourceManager.GetString("stringCargoApprove", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Check Complete.
        '''</summary>
        Public Shared ReadOnly Property stringCheckComplete() As String
            Get
                Return ResourceManager.GetString("stringCheckComplete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please Check Container No..
        '''</summary>
        Public Shared ReadOnly Property stringCheckContainerNo() As String
            Get
                Return ResourceManager.GetString("stringCheckContainerNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please Check Driver Full Name.
        '''</summary>
        Public Shared ReadOnly Property stringCheckDriverFullName() As String
            Get
                Return ResourceManager.GetString("stringCheckDriverFullName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please Check ES Seal No..
        '''</summary>
        Public Shared ReadOnly Property stringCheckESSealNo() As String
            Get
                Return ResourceManager.GetString("stringCheckESSealNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Check Fail.
        '''</summary>
        Public Shared ReadOnly Property stringCheckFail() As String
            Get
                Return ResourceManager.GetString("stringCheckFail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Check Failure .
        '''</summary>
        Public Shared ReadOnly Property stringCheckFailure() As String
            Get
                Return ResourceManager.GetString("stringCheckFailure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please Check Internal Seal No..
        '''</summary>
        Public Shared ReadOnly Property stringCheckInternalSealNo() As String
            Get
                Return ResourceManager.GetString("stringCheckInternalSealNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please Check Liner&apos;s Seal No..
        '''</summary>
        Public Shared ReadOnly Property stringCheckLinerSealNo() As String
            Get
                Return ResourceManager.GetString("stringCheckLinerSealNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please Check PM Code.
        '''</summary>
        Public Shared ReadOnly Property stringCheckPMCode() As String
            Get
                Return ResourceManager.GetString("stringCheckPMCode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please Check PM Registration Plate.
        '''</summary>
        Public Shared ReadOnly Property stringCheckPMRegistrationPlate() As String
            Get
                Return ResourceManager.GetString("stringCheckPMRegistrationPlate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure you want to exit?.
        '''</summary>
        Public Shared ReadOnly Property stringCheckQuit() As String
            Get
                Return ResourceManager.GetString("stringCheckQuit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please Check Security Check.
        '''</summary>
        Public Shared ReadOnly Property stringCheckSecurityCheck() As String
            Get
                Return ResourceManager.GetString("stringCheckSecurityCheck", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please Check Temporary Seal No..
        '''</summary>
        Public Shared ReadOnly Property stringCheckTemporarySealNo() As String
            Get
                Return ResourceManager.GetString("stringCheckTemporarySealNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Close Application.
        '''</summary>
        Public Shared ReadOnly Property stringCloseApplication() As String
            Get
                Return ResourceManager.GetString("stringCloseApplication", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Complete.
        '''</summary>
        Public Shared ReadOnly Property stringComplete() As String
            Get
                Return ResourceManager.GetString("stringComplete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Driver Validation Fail.
        '''</summary>
        Public Shared ReadOnly Property stringDriverValidationFail() As String
            Get
                Return ResourceManager.GetString("stringDriverValidationFail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Driver Validation Pass.
        '''</summary>
        Public Shared ReadOnly Property stringDriverValidationPass() As String
            Get
                Return ResourceManager.GetString("stringDriverValidationPass", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please Fill In Net Cargo Weight Field .
        '''</summary>
        Public Shared ReadOnly Property stringFillCargoWeight() As String
            Get
                Return ResourceManager.GetString("stringFillCargoWeight", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please Imform Shipping Admin.
        '''</summary>
        Public Shared ReadOnly Property stringInformShippingAdmin() As String
            Get
                Return ResourceManager.GetString("stringInformShippingAdmin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please Inform Warehouse Admin.
        '''</summary>
        Public Shared ReadOnly Property stringInformWarehouseAdmin() As String
            Get
                Return ResourceManager.GetString("stringInformWarehouseAdmin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ISO Approve.
        '''</summary>
        Public Shared ReadOnly Property stringISOApprove() As String
            Get
                Return ResourceManager.GetString("stringISOApprove", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ISO Check.
        '''</summary>
        Public Shared ReadOnly Property stringISOCheck() As String
            Get
                Return ResourceManager.GetString("stringISOCheck", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ISO Security Check Complete.
        '''</summary>
        Public Shared ReadOnly Property stringISOCheckComplete() As String
            Get
                Return ResourceManager.GetString("stringISOCheckComplete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ISO Check Failed.
        '''</summary>
        Public Shared ReadOnly Property stringISOCheckFailed() As String
            Get
                Return ResourceManager.GetString("stringISOCheckFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Net Cargo Weight Check Failed.
        '''</summary>
        Public Shared ReadOnly Property stringNetCargoCheckFailed() As String
            Get
                Return ResourceManager.GetString("stringNetCargoCheckFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Post Complete.
        '''</summary>
        Public Shared ReadOnly Property stringPostComplete() As String
            Get
                Return ResourceManager.GetString("stringPostComplete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Post Failed.
        '''</summary>
        Public Shared ReadOnly Property stringPostFailed() As String
            Get
                Return ResourceManager.GetString("stringPostFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Security Check.
        '''</summary>
        Public Shared ReadOnly Property stringSecurityCheck() As String
            Get
                Return ResourceManager.GetString("stringSecurityCheck", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Security Check Complete.
        '''</summary>
        Public Shared ReadOnly Property stringSecurityCheckComplete() As String
            Get
                Return ResourceManager.GetString("stringSecurityCheckComplete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stop CTNR / Inform Warehouse.
        '''</summary>
        Public Shared ReadOnly Property stringStopCTNR() As String
            Get
                Return ResourceManager.GetString("stringStopCTNR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Truck Out Date Error.
        '''</summary>
        Public Shared ReadOnly Property stringTruckOutDateError() As String
            Get
                Return ResourceManager.GetString("stringTruckOutDateError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Update Complete.
        '''</summary>
        Public Shared ReadOnly Property stringUpdateComplete() As String
            Get
                Return ResourceManager.GetString("stringUpdateComplete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Update Failure.
        '''</summary>
        Public Shared ReadOnly Property stringUpdateFailure() As String
            Get
                Return ResourceManager.GetString("stringUpdateFailure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Validation Fail.
        '''</summary>
        Public Shared ReadOnly Property stringValidationFail() As String
            Get
                Return ResourceManager.GetString("stringValidationFail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Validation Pass.
        '''</summary>
        Public Shared ReadOnly Property stringValidationPass() As String
            Get
                Return ResourceManager.GetString("stringValidationPass", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
