'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class ResourceLoginFrench
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Truck_Out_Order.ResourceLoginFrench", GetType(ResourceLoginFrench).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Annuler.
        '''</summary>
        Public Shared ReadOnly Property btnCancel() As String
            Get
                Return ResourceManager.GetString("btnCancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to S&apos;identifier.
        '''</summary>
        Public Shared ReadOnly Property btnLogin() As String
            Get
                Return ResourceManager.GetString("btnLogin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Connexion au compte.
        '''</summary>
        Public Shared ReadOnly Property lblLogin() As String
            Get
                Return ResourceManager.GetString("lblLogin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mot de passe.
        '''</summary>
        Public Shared ReadOnly Property lblPassword() As String
            Get
                Return ResourceManager.GetString("lblPassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Système TOO.
        '''</summary>
        Public Shared ReadOnly Property lblTOOSystem() As String
            Get
                Return ResourceManager.GetString("lblTOOSystem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nom d&apos;utilisateur.
        '''</summary>
        Public Shared ReadOnly Property lblUsername() As String
            Get
                Return ResourceManager.GetString("lblUsername", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Erreur d&apos;authentification.
        '''</summary>
        Public Shared ReadOnly Property stringAuthentificationError() As String
            Get
                Return ResourceManager.GetString("stringAuthentificationError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Le mot de passe ne correspond pas à l&apos;enregistrement.
        '''</summary>
        Public Shared ReadOnly Property stringDoNotMatch() As String
            Get
                Return ResourceManager.GetString("stringDoNotMatch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Veuillez remplir le champ requis.
        '''</summary>
        Public Shared ReadOnly Property stringRequired() As String
            Get
                Return ResourceManager.GetString("stringRequired", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cet utilisateur est désactivé.
        '''</summary>
        Public Shared ReadOnly Property stringUserDisabled() As String
            Get
                Return ResourceManager.GetString("stringUserDisabled", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
