'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class ResourceShippingEditFrench
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Truck_Out_Order.ResourceShippingEditFrench", GetType(ResourceShippingEditFrench).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Annuler.
        '''</summary>
        Friend Shared ReadOnly Property btnCancel() As String
            Get
                Return ResourceManager.GetString("btnCancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Poste.
        '''</summary>
        Friend Shared ReadOnly Property btnPost() As String
            Get
                Return ResourceManager.GetString("btnPost", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Imprimer.
        '''</summary>
        Friend Shared ReadOnly Property btnPrint() As String
            Get
                Return ResourceManager.GetString("btnPrint", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sauvegarder.
        '''</summary>
        Friend Shared ReadOnly Property btnSave() As String
            Get
                Return ResourceManager.GetString("btnSave", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Compagnie:.
        '''</summary>
        Friend Shared ReadOnly Property lblCompnay() As String
            Get
                Return ResourceManager.GetString("lblCompnay", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Numéro de conteneur.
        '''</summary>
        Friend Shared ReadOnly Property lblContainerNo() As String
            Get
                Return ResourceManager.GetString("lblContainerNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Taille du conteneur:.
        '''</summary>
        Friend Shared ReadOnly Property lblContainerSize() As String
            Get
                Return ResourceManager.GetString("lblContainerSize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DDB:.
        '''</summary>
        Friend Shared ReadOnly Property lblDDB() As String
            Get
                Return ResourceManager.GetString("lblDDB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Numéro de sceau ES.
        '''</summary>
        Friend Shared ReadOnly Property lblEsSealNo() As String
            Get
                Return ResourceManager.GetString("lblEsSealNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nom complet de l&apos;entreprise:.
        '''</summary>
        Friend Shared ReadOnly Property lblFullName() As String
            Get
                Return ResourceManager.GetString("lblFullName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Transporteur:.
        '''</summary>
        Friend Shared ReadOnly Property lblHaulier() As String
            Get
                Return ResourceManager.GetString("lblHaulier", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Numéro de joint interne.
        '''</summary>
        Friend Shared ReadOnly Property lblInternalSealNo() As String
            Get
                Return ResourceManager.GetString("lblInternalSealNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Facture d&apos;achat:.
        '''</summary>
        Friend Shared ReadOnly Property lblInvoice() As String
            Get
                Return ResourceManager.GetString("lblInvoice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Réservoir ISO:.
        '''</summary>
        Friend Shared ReadOnly Property lblISOTank() As String
            Get
                Return ResourceManager.GetString("lblISOTank", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Poids du réservoir ISO (mt):.
        '''</summary>
        Friend Shared ReadOnly Property lblISOTankWeight() As String
            Get
                Return ResourceManager.GetString("lblISOTankWeight", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Date de sortie du camion:.
        '''</summary>
        Friend Shared ReadOnly Property lblISOTruckOutDate() As String
            Get
                Return ResourceManager.GetString("lblISOTruckOutDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chargement de la date de fin.
        '''</summary>
        Friend Shared ReadOnly Property lblLCD() As String
            Get
                Return ResourceManager.GetString("lblLCD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Temps de chargement terminé.
        '''</summary>
        Friend Shared ReadOnly Property lblLCT() As String
            Get
                Return ResourceManager.GetString("lblLCT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Numéro de joint de revêtement.
        '''</summary>
        Friend Shared ReadOnly Property lblLinerSealNo() As String
            Get
                Return ResourceManager.GetString("lblLinerSealNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Quai de chargement:.
        '''</summary>
        Friend Shared ReadOnly Property lblLoadingBay() As String
            Get
                Return ResourceManager.GetString("lblLoadingBay", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Port de chargement:.
        '''</summary>
        Friend Shared ReadOnly Property lblLoadingPort() As String
            Get
                Return ResourceManager.GetString("lblLoadingPort", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Poids net de la cargaison (kg):.
        '''</summary>
        Friend Shared ReadOnly Property lblNetCargoWeight() As String
            Get
                Return ResourceManager.GetString("lblNetCargoWeight", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nom complet du port de chargement:.
        '''</summary>
        Friend Shared ReadOnly Property lblPortFullName() As String
            Get
                Return ResourceManager.GetString("lblPortFullName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Produit:.
        '''</summary>
        Friend Shared ReadOnly Property lblProduct() As String
            Get
                Return ResourceManager.GetString("lblProduct", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Date de sortie du camion prêt.
        '''</summary>
        Friend Shared ReadOnly Property lblRTD() As String
            Get
                Return ResourceManager.GetString("lblRTD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Temps de sortie du camion prêt.
        '''</summary>
        Friend Shared ReadOnly Property lblRTT() As String
            Get
                Return ResourceManager.GetString("lblRTT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Date limite d&apos;expédition:.
        '''</summary>
        Friend Shared ReadOnly Property lblSCD() As String
            Get
                Return ResourceManager.GetString("lblSCD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Heure de clôture de l&apos;expédition:.
        '''</summary>
        Friend Shared ReadOnly Property lblSCT() As String
            Get
                Return ResourceManager.GetString("lblSCT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Poste de sécurité.
        '''</summary>
        Friend Shared ReadOnly Property lblSecurityPost() As String
            Get
                Return ResourceManager.GetString("lblSecurityPost", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Envoyer à l&apos;entreprise:.
        '''</summary>
        Friend Shared ReadOnly Property lblSendToCompany() As String
            Get
                Return ResourceManager.GetString("lblSendToCompany", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ligne maritime:.
        '''</summary>
        Friend Shared ReadOnly Property lblShippingLine() As String
            Get
                Return ResourceManager.GetString("lblShippingLine", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Poste d&apos;expédition.
        '''</summary>
        Friend Shared ReadOnly Property lblShippingPost() As String
            Get
                Return ResourceManager.GetString("lblShippingPost", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Numéro de sceau temporaire.
        '''</summary>
        Friend Shared ReadOnly Property lblTemporarySealNo() As String
            Get
                Return ResourceManager.GetString("lblTemporarySealNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Numéro de sortie du camion:.
        '''</summary>
        Friend Shared ReadOnly Property lblTruckOutNumber() As String
            Get
                Return ResourceManager.GetString("lblTruckOutNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Emplacement de l&apos;entrepôt:.
        '''</summary>
        Friend Shared ReadOnly Property lblWarehouseLocation() As String
            Get
                Return ResourceManager.GetString("lblWarehouseLocation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Poste d&apos;entrepôt.
        '''</summary>
        Friend Shared ReadOnly Property lblWarehousePost() As String
            Get
                Return ResourceManager.GetString("lblWarehousePost", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Veuillez ne remplir que des nombres entiers dans le poids net de la cargaison / Veuillez remplir le champ du poids net de la cargaison.
        '''</summary>
        Friend Shared ReadOnly Property stringCargoWeightEx() As String
            Get
                Return ResourceManager.GetString("stringCargoWeightEx", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fermer l&apos;application.
        '''</summary>
        Friend Shared ReadOnly Property stringCloseApplication() As String
            Get
                Return ResourceManager.GetString("stringCloseApplication", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Complété.
        '''</summary>
        Friend Shared ReadOnly Property stringComplete() As String
            Get
                Return ResourceManager.GetString("stringComplete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Veuillez remplir le champ de l&apos;entreprise.
        '''</summary>
        Friend Shared ReadOnly Property stringFillCompany() As String
            Get
                Return ResourceManager.GetString("stringFillCompany", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Veuillez remplir le champ du numéro de conteneur.
        '''</summary>
        Friend Shared ReadOnly Property stringFillContainerNo() As String
            Get
                Return ResourceManager.GetString("stringFillContainerNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Veuillez remplir le champ Taille du conteneur.
        '''</summary>
        Friend Shared ReadOnly Property stringFillContainerSize() As String
            Get
                Return ResourceManager.GetString("stringFillContainerSize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Veuillez remplir le champ DDB.
        '''</summary>
        Friend Shared ReadOnly Property stringFillDDB() As String
            Get
                Return ResourceManager.GetString("stringFillDDB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Veuillez remplir le champ du transporteur.
        '''</summary>
        Friend Shared ReadOnly Property stringFillHaulier() As String
            Get
                Return ResourceManager.GetString("stringFillHaulier", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Veuillez remplir le champ du numéro de sceau interne.
        '''</summary>
        Friend Shared ReadOnly Property stringFillInternalSealNo() As String
            Get
                Return ResourceManager.GetString("stringFillInternalSealNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Veuillez remplir le champ de la facture.
        '''</summary>
        Friend Shared ReadOnly Property stringFillInvoice() As String
            Get
                Return ResourceManager.GetString("stringFillInvoice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ResourceNewPage.
        '''</summary>
        Friend Shared ReadOnly Property stringFillISOTankWeight() As String
            Get
                Return ResourceManager.GetString("stringFillISOTankWeight", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Veuillez remplir le champ ISO Truck Out Date.
        '''</summary>
        Friend Shared ReadOnly Property stringFillISOTOD() As String
            Get
                Return ResourceManager.GetString("stringFillISOTOD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Veuillez remplir le champ du numéro de joint de revêtement.
        '''</summary>
        Friend Shared ReadOnly Property stringFillLinerSealNo() As String
            Get
                Return ResourceManager.GetString("stringFillLinerSealNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Veuillez remplir le champ du port de chargement.
        '''</summary>
        Friend Shared ReadOnly Property stringFillLoadingPort() As String
            Get
                Return ResourceManager.GetString("stringFillLoadingPort", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Veuillez remplir le champ du produit.
        '''</summary>
        Friend Shared ReadOnly Property stringFillProduct() As String
            Get
                Return ResourceManager.GetString("stringFillProduct", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Veuillez remplir le champ Type de produit.
        '''</summary>
        Friend Shared ReadOnly Property stringFillProductType() As String
            Get
                Return ResourceManager.GetString("stringFillProductType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Veuillez remplir le champ Date de clôture de l&apos;envoi.
        '''</summary>
        Friend Shared ReadOnly Property stringFillSCD() As String
            Get
                Return ResourceManager.GetString("stringFillSCD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Veuillez remplir l&apos;heure de clôture de l&apos;expédition.
        '''</summary>
        Friend Shared ReadOnly Property stringFillSCT() As String
            Get
                Return ResourceManager.GetString("stringFillSCT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Veuillez remplir le champ de la ligne d&apos;expédition.
        '''</summary>
        Friend Shared ReadOnly Property stringFillShippingLine() As String
            Get
                Return ResourceManager.GetString("stringFillShippingLine", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Veuillez remplir le champ du numéro de sceau temporaire.
        '''</summary>
        Friend Shared ReadOnly Property stringFillTempSealNo() As String
            Get
                Return ResourceManager.GetString("stringFillTempSealNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Post terminé en tant que.
        '''</summary>
        Friend Shared ReadOnly Property stringPostCompleteAs() As String
            Get
                Return ResourceManager.GetString("stringPostCompleteAs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ce numéro est publié. Veuillez contacter l&apos;administrateur pour la modification.
        '''</summary>
        Friend Shared ReadOnly Property stringPosted() As String
            Get
                Return ResourceManager.GetString("stringPosted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Êtes-vous sûr de vouloir quitter?.
        '''</summary>
        Friend Shared ReadOnly Property stringQuitChecking() As String
            Get
                Return ResourceManager.GetString("stringQuitChecking", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enregistrer la fin sous.
        '''</summary>
        Friend Shared ReadOnly Property stringSaveCompleteAs() As String
            Get
                Return ResourceManager.GetString("stringSaveCompleteAs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Échec de la mise à jour.
        '''</summary>
        Friend Shared ReadOnly Property stringUpdateFailure() As String
            Get
                Return ResourceManager.GetString("stringUpdateFailure", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
