'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class ResourceNewPage
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Truck_Out_Order.ResourceNewPage", GetType(ResourceNewPage).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancel.
        '''</summary>
        Friend Shared ReadOnly Property btnCancel() As String
            Get
                Return ResourceManager.GetString("btnCancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Post.
        '''</summary>
        Friend Shared ReadOnly Property btnPost() As String
            Get
                Return ResourceManager.GetString("btnPost", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save.
        '''</summary>
        Friend Shared ReadOnly Property btnSave() As String
            Get
                Return ResourceManager.GetString("btnSave", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Company:.
        '''</summary>
        Friend Shared ReadOnly Property lblCompany() As String
            Get
                Return ResourceManager.GetString("lblCompany", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Container No..
        '''</summary>
        Friend Shared ReadOnly Property lblContainerNo() As String
            Get
                Return ResourceManager.GetString("lblContainerNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Container Size:.
        '''</summary>
        Friend Shared ReadOnly Property lblContainerSize() As String
            Get
                Return ResourceManager.GetString("lblContainerSize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DDB:.
        '''</summary>
        Friend Shared ReadOnly Property lblDDB() As String
            Get
                Return ResourceManager.GetString("lblDDB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ES Seal No..
        '''</summary>
        Friend Shared ReadOnly Property lblEsSealNo() As String
            Get
                Return ResourceManager.GetString("lblEsSealNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Company Full Name:.
        '''</summary>
        Friend Shared ReadOnly Property lblFullName() As String
            Get
                Return ResourceManager.GetString("lblFullName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Haulier:.
        '''</summary>
        Friend Shared ReadOnly Property lblHaulier() As String
            Get
                Return ResourceManager.GetString("lblHaulier", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Internal Seal No..
        '''</summary>
        Friend Shared ReadOnly Property lblInternalSealNo() As String
            Get
                Return ResourceManager.GetString("lblInternalSealNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invoice:.
        '''</summary>
        Friend Shared ReadOnly Property lblInvoice() As String
            Get
                Return ResourceManager.GetString("lblInvoice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ISO Tank:.
        '''</summary>
        Friend Shared ReadOnly Property lblISOTank() As String
            Get
                Return ResourceManager.GetString("lblISOTank", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ISO Tank Weight (mt):.
        '''</summary>
        Friend Shared ReadOnly Property lblISOTankWeight() As String
            Get
                Return ResourceManager.GetString("lblISOTankWeight", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Truck Out Date:.
        '''</summary>
        Friend Shared ReadOnly Property lblISOTruckOutDate() As String
            Get
                Return ResourceManager.GetString("lblISOTruckOutDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Liner&apos;s Seal No..
        '''</summary>
        Friend Shared ReadOnly Property lblLinerSealNo() As String
            Get
                Return ResourceManager.GetString("lblLinerSealNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Loading Bay:.
        '''</summary>
        Friend Shared ReadOnly Property lblLoadingBay() As String
            Get
                Return ResourceManager.GetString("lblLoadingBay", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Loading Port:.
        '''</summary>
        Friend Shared ReadOnly Property lblLoadingPort() As String
            Get
                Return ResourceManager.GetString("lblLoadingPort", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Net Cargo Weight (kg):.
        '''</summary>
        Friend Shared ReadOnly Property lblNetCargoWeight() As String
            Get
                Return ResourceManager.GetString("lblNetCargoWeight", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Loading Port Full Name:.
        '''</summary>
        Friend Shared ReadOnly Property lblPortFullName() As String
            Get
                Return ResourceManager.GetString("lblPortFullName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Product:.
        '''</summary>
        Friend Shared ReadOnly Property lblProduct() As String
            Get
                Return ResourceManager.GetString("lblProduct", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Shipment Closing Date:.
        '''</summary>
        Friend Shared ReadOnly Property lblSCD() As String
            Get
                Return ResourceManager.GetString("lblSCD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Shipment Closing Time:.
        '''</summary>
        Friend Shared ReadOnly Property lblSCT() As String
            Get
                Return ResourceManager.GetString("lblSCT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Send To Company:.
        '''</summary>
        Friend Shared ReadOnly Property lblSendToCompany() As String
            Get
                Return ResourceManager.GetString("lblSendToCompany", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Shipping Line:.
        '''</summary>
        Friend Shared ReadOnly Property lblShippingLine() As String
            Get
                Return ResourceManager.GetString("lblShippingLine", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Temporary Seal No,.
        '''</summary>
        Friend Shared ReadOnly Property lblTemporarySealNo() As String
            Get
                Return ResourceManager.GetString("lblTemporarySealNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Truck Out Number:.
        '''</summary>
        Friend Shared ReadOnly Property lblTruckOutNumber() As String
            Get
                Return ResourceManager.GetString("lblTruckOutNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Warehouse Location:.
        '''</summary>
        Friend Shared ReadOnly Property lblWarehouseLocation() As String
            Get
                Return ResourceManager.GetString("lblWarehouseLocation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please Only Enter Integer In Net Cargo Weight.
        '''</summary>
        Friend Shared ReadOnly Property stringCargoWeightEx() As String
            Get
                Return ResourceManager.GetString("stringCargoWeightEx", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Close Application.
        '''</summary>
        Friend Shared ReadOnly Property stringCloseApplication() As String
            Get
                Return ResourceManager.GetString("stringCloseApplication", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Complete.
        '''</summary>
        Friend Shared ReadOnly Property stringComplete() As String
            Get
                Return ResourceManager.GetString("stringComplete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please Fill In The Company Field.
        '''</summary>
        Friend Shared ReadOnly Property stringFillCompany() As String
            Get
                Return ResourceManager.GetString("stringFillCompany", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please Fill In The Container No. Field.
        '''</summary>
        Friend Shared ReadOnly Property stringFillContainerNo() As String
            Get
                Return ResourceManager.GetString("stringFillContainerNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please Fill In The Container Size Field.
        '''</summary>
        Friend Shared ReadOnly Property stringFillContainerSize() As String
            Get
                Return ResourceManager.GetString("stringFillContainerSize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please Fill In The DDB Field.
        '''</summary>
        Friend Shared ReadOnly Property stringFillDDB() As String
            Get
                Return ResourceManager.GetString("stringFillDDB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please Fill In The Haulier Field.
        '''</summary>
        Friend Shared ReadOnly Property stringFillHaulier() As String
            Get
                Return ResourceManager.GetString("stringFillHaulier", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please Fill In The Internal Seal No. Field.
        '''</summary>
        Friend Shared ReadOnly Property stringFillInternalSealNo() As String
            Get
                Return ResourceManager.GetString("stringFillInternalSealNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please Fill In The Invoice Field.
        '''</summary>
        Friend Shared ReadOnly Property stringFillInvoice() As String
            Get
                Return ResourceManager.GetString("stringFillInvoice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please Fill In The ISO Tank Weight Field.
        '''</summary>
        Friend Shared ReadOnly Property stringFillISOTankWeight() As String
            Get
                Return ResourceManager.GetString("stringFillISOTankWeight", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please Fill In The ISO Truck Out Date Field.
        '''</summary>
        Friend Shared ReadOnly Property stringFillISOTOD() As String
            Get
                Return ResourceManager.GetString("stringFillISOTOD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please Fill In The Liner Seal No. Field.
        '''</summary>
        Friend Shared ReadOnly Property stringFillLinerSealNo() As String
            Get
                Return ResourceManager.GetString("stringFillLinerSealNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please Fill In The Loading Port Field.
        '''</summary>
        Friend Shared ReadOnly Property stringFillLoadingPort() As String
            Get
                Return ResourceManager.GetString("stringFillLoadingPort", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please Fill In The Product Field.
        '''</summary>
        Friend Shared ReadOnly Property stringFillProduct() As String
            Get
                Return ResourceManager.GetString("stringFillProduct", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please Fill In The Product Type Field.
        '''</summary>
        Friend Shared ReadOnly Property stringFillProductType() As String
            Get
                Return ResourceManager.GetString("stringFillProductType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please Fill In The Shipment Closing Date Field.
        '''</summary>
        Friend Shared ReadOnly Property stringFillSCD() As String
            Get
                Return ResourceManager.GetString("stringFillSCD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please Fill In The Shipment Closing Time Field.
        '''</summary>
        Friend Shared ReadOnly Property stringFillSCT() As String
            Get
                Return ResourceManager.GetString("stringFillSCT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please Fill In The Shipping Line Field.
        '''</summary>
        Friend Shared ReadOnly Property stringFillShippingLine() As String
            Get
                Return ResourceManager.GetString("stringFillShippingLine", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please Fill In The Temporary Seal No. Field.
        '''</summary>
        Friend Shared ReadOnly Property stringFillTempSealNo() As String
            Get
                Return ResourceManager.GetString("stringFillTempSealNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Post Complete As.
        '''</summary>
        Friend Shared ReadOnly Property stringPostCompleteAs() As String
            Get
                Return ResourceManager.GetString("stringPostCompleteAs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure you want to quit?.
        '''</summary>
        Friend Shared ReadOnly Property stringQuitChecking() As String
            Get
                Return ResourceManager.GetString("stringQuitChecking", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save Complete As.
        '''</summary>
        Friend Shared ReadOnly Property stringSaveCompleteAs() As String
            Get
                Return ResourceManager.GetString("stringSaveCompleteAs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Update Failure.
        '''</summary>
        Friend Shared ReadOnly Property stringUpdateFailure() As String
            Get
                Return ResourceManager.GetString("stringUpdateFailure", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
