'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class ResourceCompanyMaintenance
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Truck_Out_Order.ResourceCompanyMaintenance", GetType(ResourceCompanyMaintenance).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancel.
        '''</summary>
        Friend Shared ReadOnly Property btnCancel() As String
            Get
                Return ResourceManager.GetString("btnCancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Delete.
        '''</summary>
        Friend Shared ReadOnly Property btnDel() As String
            Get
                Return ResourceManager.GetString("btnDel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New.
        '''</summary>
        Friend Shared ReadOnly Property btnNew() As String
            Get
                Return ResourceManager.GetString("btnNew", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save.
        '''</summary>
        Friend Shared ReadOnly Property btnSave() As String
            Get
                Return ResourceManager.GetString("btnSave", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save.
        '''</summary>
        Friend Shared ReadOnly Property btnTOOSave() As String
            Get
                Return ResourceManager.GetString("btnTOOSave", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Address Line 1:.
        '''</summary>
        Friend Shared ReadOnly Property lblAddressLine1() As String
            Get
                Return ResourceManager.GetString("lblAddressLine1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Address Line 2:.
        '''</summary>
        Friend Shared ReadOnly Property lblAddressLine2() As String
            Get
                Return ResourceManager.GetString("lblAddressLine2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to City:.
        '''</summary>
        Friend Shared ReadOnly Property lblCIty() As String
            Get
                Return ResourceManager.GetString("lblCIty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Company Name:.
        '''</summary>
        Friend Shared ReadOnly Property lblCompanyFullName() As String
            Get
                Return ResourceManager.GetString("lblCompanyFullName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Company Maintenance.
        '''</summary>
        Friend Shared ReadOnly Property lblCompanyMaintenance() As String
            Get
                Return ResourceManager.GetString("lblCompanyMaintenance", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Company Registration No..
        '''</summary>
        Friend Shared ReadOnly Property lblCompanyRegistrationNo() As String
            Get
                Return ResourceManager.GetString("lblCompanyRegistrationNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Country:.
        '''</summary>
        Friend Shared ReadOnly Property lblCountry() As String
            Get
                Return ResourceManager.GetString("lblCountry", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fax:.
        '''</summary>
        Friend Shared ReadOnly Property lblFax() As String
            Get
                Return ResourceManager.GetString("lblFax", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New TOO Number:.
        '''</summary>
        Friend Shared ReadOnly Property lblNewNumber() As String
            Get
                Return ResourceManager.GetString("lblNewNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Postal Code:.
        '''</summary>
        Friend Shared ReadOnly Property lblPostalCode() As String
            Get
                Return ResourceManager.GetString("lblPostalCode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to State:.
        '''</summary>
        Friend Shared ReadOnly Property lblState() As String
            Get
                Return ResourceManager.GetString("lblState", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Telephone:.
        '''</summary>
        Friend Shared ReadOnly Property lblTelephone() As String
            Get
                Return ResourceManager.GetString("lblTelephone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Authentication.
        '''</summary>
        Friend Shared ReadOnly Property stringAuthentication() As String
            Get
                Return ResourceManager.GetString("stringAuthentication", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure you want to delete?.
        '''</summary>
        Friend Shared ReadOnly Property stringCheckDelete() As String
            Get
                Return ResourceManager.GetString("stringCheckDelete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Update Complete.
        '''</summary>
        Friend Shared ReadOnly Property stringComplete() As String
            Get
                Return ResourceManager.GetString("stringComplete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Current Latest TOO Number is.
        '''</summary>
        Friend Shared ReadOnly Property stringCurrentMaxNum() As String
            Get
                Return ResourceManager.GetString("stringCurrentMaxNum", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Delete Complete.
        '''</summary>
        Friend Shared ReadOnly Property stringDelete() As String
            Get
                Return ResourceManager.GetString("stringDelete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error.
        '''</summary>
        Friend Shared ReadOnly Property stringError() As String
            Get
                Return ResourceManager.GetString("stringError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The new TOO Number can&apos;t less than existing TOO Number.
        '''</summary>
        Friend Shared ReadOnly Property stringErrorLessThanExistingNumber() As String
            Get
                Return ResourceManager.GetString("stringErrorLessThanExistingNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please fill the required field.
        '''</summary>
        Friend Shared ReadOnly Property stringFillRequired() As String
            Get
                Return ResourceManager.GetString("stringFillRequired", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The new TOO Number is.
        '''</summary>
        Friend Shared ReadOnly Property stringNewTOONumberIs() As String
            Get
                Return ResourceManager.GetString("stringNewTOONumberIs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Update Failed.
        '''</summary>
        Friend Shared ReadOnly Property stringUpdateFailed() As String
            Get
                Return ResourceManager.GetString("stringUpdateFailed", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
