'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class ResourceCompanyMaintenanceFrench
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Truck_Out_Order.ResourceCompanyMaintenanceFrench", GetType(ResourceCompanyMaintenanceFrench).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Annuler.
        '''</summary>
        Friend Shared ReadOnly Property btnCancel() As String
            Get
                Return ResourceManager.GetString("btnCancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Effacer.
        '''</summary>
        Friend Shared ReadOnly Property btnDel() As String
            Get
                Return ResourceManager.GetString("btnDel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nouveau.
        '''</summary>
        Friend Shared ReadOnly Property btnNew() As String
            Get
                Return ResourceManager.GetString("btnNew", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sauver.
        '''</summary>
        Friend Shared ReadOnly Property btnSave() As String
            Get
                Return ResourceManager.GetString("btnSave", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sauver.
        '''</summary>
        Friend Shared ReadOnly Property btnTOOSave() As String
            Get
                Return ResourceManager.GetString("btnTOOSave", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Adresse Ligne 1:.
        '''</summary>
        Friend Shared ReadOnly Property lblAddressLine1() As String
            Get
                Return ResourceManager.GetString("lblAddressLine1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Adresse Ligne 2:.
        '''</summary>
        Friend Shared ReadOnly Property lblAddressLine2() As String
            Get
                Return ResourceManager.GetString("lblAddressLine2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ville:.
        '''</summary>
        Friend Shared ReadOnly Property lblCity() As String
            Get
                Return ResourceManager.GetString("lblCity", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nom complet de l&apos;entreprise:.
        '''</summary>
        Friend Shared ReadOnly Property lblCompanyFullName() As String
            Get
                Return ResourceManager.GetString("lblCompanyFullName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Entretien de l&apos;entreprise.
        '''</summary>
        Friend Shared ReadOnly Property lblCompanyMaintenance() As String
            Get
                Return ResourceManager.GetString("lblCompanyMaintenance", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Numéro d&apos;entreprise:.
        '''</summary>
        Friend Shared ReadOnly Property lblCompanyRegistrationNo() As String
            Get
                Return ResourceManager.GetString("lblCompanyRegistrationNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to De campagne:.
        '''</summary>
        Friend Shared ReadOnly Property lblCountry() As String
            Get
                Return ResourceManager.GetString("lblCountry", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fax:.
        '''</summary>
        Friend Shared ReadOnly Property lblFax() As String
            Get
                Return ResourceManager.GetString("lblFax", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Le nouveau numéro d&apos;expédition est:.
        '''</summary>
        Friend Shared ReadOnly Property lblNewNumber() As String
            Get
                Return ResourceManager.GetString("lblNewNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Code Postal:.
        '''</summary>
        Friend Shared ReadOnly Property lblPostalCode() As String
            Get
                Return ResourceManager.GetString("lblPostalCode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to État:.
        '''</summary>
        Friend Shared ReadOnly Property lblState() As String
            Get
                Return ResourceManager.GetString("lblState", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Numéro de téléphone:.
        '''</summary>
        Friend Shared ReadOnly Property lblTelephone() As String
            Get
                Return ResourceManager.GetString("lblTelephone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Authentification.
        '''</summary>
        Friend Shared ReadOnly Property stringAuthentication() As String
            Get
                Return ResourceManager.GetString("stringAuthentication", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Etes-vous sûr que vous voulez supprimer?.
        '''</summary>
        Friend Shared ReadOnly Property stringCheckDelete() As String
            Get
                Return ResourceManager.GetString("stringCheckDelete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mise à jour terminée.
        '''</summary>
        Friend Shared ReadOnly Property stringComplete() As String
            Get
                Return ResourceManager.GetString("stringComplete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Le dernier numéro d&apos;expédition actuel est.
        '''</summary>
        Friend Shared ReadOnly Property stringCurrentMaxNum() As String
            Get
                Return ResourceManager.GetString("stringCurrentMaxNum", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Supprimer terminé.
        '''</summary>
        Friend Shared ReadOnly Property stringDelete() As String
            Get
                Return ResourceManager.GetString("stringDelete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Erreur.
        '''</summary>
        Friend Shared ReadOnly Property stringError() As String
            Get
                Return ResourceManager.GetString("stringError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Le nouveau numéro d&apos;expédition ne peut pas être inférieur au numéro d&apos;expédition existant.
        '''</summary>
        Friend Shared ReadOnly Property stringErrorLessThanExistingNumber() As String
            Get
                Return ResourceManager.GetString("stringErrorLessThanExistingNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Veuillez remplir le champ requis.
        '''</summary>
        Friend Shared ReadOnly Property stringFillRequired() As String
            Get
                Return ResourceManager.GetString("stringFillRequired", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Le nouveau numéro d&apos;expédition est.
        '''</summary>
        Friend Shared ReadOnly Property stringNewTOONumberIs() As String
            Get
                Return ResourceManager.GetString("stringNewTOONumberIs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mise à jour a échoué.
        '''</summary>
        Friend Shared ReadOnly Property stringUpdateFailed() As String
            Get
                Return ResourceManager.GetString("stringUpdateFailed", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
